apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}
  annotations:
    configmap.reloader.stakater.com/reload: {{ .Values.collectorConfigMap.name }}
  name: {{ .Values.app.name }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: {{ .Values.app.name }}
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: collectors
          mountPath: "/tmp/collectors"
          readOnly: true
        resources:
            limits:
              memory: {{ .Values.memlimit }}
            requests:
              memory: {{ .Values.memlimit }}
      serviceAccountName: mock-app-service-account
      volumes:
      - name: collectors
        configMap:
          name: {{ .Values.collectorConfigMap.name }}