apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-service
  namespace: sysviewer
spec:
  type: ClusterIP
  selector:
    component: app
  ports:
    - name: http
      port: 8000
      targetPort: 8000
