apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
  namespace: sysviewer
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
