apiVersion: v1
kind: Service
metadata:
  name: node-port-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    component: app
  ports:
    - port: 8000
      targetPort: 8000
#      nodePort: 32443
