apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-sysview
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-sysview
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: k8s/helm/charts/sysview-chart
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - allowEmpty=true
    - CreateNamespace=true